;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Source
DestinationPath=Content/Localization/Source
ManifestName=Source.manifest
ArchiveName=Source.archive
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=ko

[GatherTextStep0]
CommandletClass=GatherTextFromSource
ExcludePathFilters=Config/Localization/*
ExcludePathFilters=Source/*
FileNameFilters=*.h
FileNameFilters=*.cpp
FileNameFilters=*.ini
ShouldGatherFromEditorOnlyData=false

[GatherTextStep1]
CommandletClass=GenerateGatherManifest

[GatherTextStep2]
CommandletClass=GenerateGatherArchive

[GatherTextStep3]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=Source.csv
bConflictReport=true
ConflictReportName=Source_Conflicts.txt

